/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.adrian.practica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author adria
 */
public class AddPedido extends javax.swing.JPanel {
    
    private MenuFrame frame;
    /**
     * Creates new form AddPedido
     */
    public AddPedido(MenuFrame frame) {
        this.frame = frame;
        initComponents();
        
        
        cargarUsuarios();
        cargarProductos();
    }
    
    
    private void cargarUsuarios() {
    
        String URL_CONEXION = "jdbc:h2:mem:testdb";
        try (Connection conn = DriverManager.getConnection(URL_CONEXION, "sa", "password")) {
            ResultSet rs = conn.createStatement().executeQuery("SELECT username FROM usuarios");
            UsuarioBox.removeAllItems();
            while(rs.next()){
                UsuarioBox.addItem(rs.getString("username"));
            }
        } catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void cargarProductos() {
        String URL_CONEXION = "jdbc:h2:mem:testdb";
        try (Connection conn = DriverManager.getConnection(URL_CONEXION, "sa", "password")) {
            ResultSet rs = conn.createStatement().executeQuery("SELECT nombre FROM productos");
            productoBox.removeAllItems();
            while(rs.next()){
                productoBox.addItem(rs.getString("nombre"));
            }
        } catch(SQLException e){
             e.printStackTrace();
            }
    }
    
    private int obtenerIdUsuario(String nombre) throws SQLException {
        String URL_CONEXION = "jdbc:h2:mem:testdb";
        try(Connection conn = DriverManager.getConnection(URL_CONEXION, "sa", "password")) {
            PreparedStatement pstmt = conn.prepareStatement("SELECT id FROM usuarios WHERE username = ?");
            pstmt.setString(1, nombre);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()) return rs.getInt("id");
        }
        return -1; // no encontrado
    }
    
    private int obtenerIdProducto(String nombre) throws SQLException {
        String URL_CONEXION = "jdbc:h2:mem:testdb";
        try(Connection conn = DriverManager.getConnection(URL_CONEXION, "sa", "password")) {
            PreparedStatement pstmt = conn.prepareStatement("SELECT id FROM productos WHERE nombre = ?");
            pstmt.setString(1, nombre);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()) return rs.getInt("id");
        }
        return -1; // no encontrado
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsuarioBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        productoBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cantidadText = new javax.swing.JTextArea();
        añadirBtn = new javax.swing.JButton();
        Atras = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir pedido");

        jLabel2.setText("Usuario");

        UsuarioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UsuarioBox.addActionListener(this::UsuarioBoxActionPerformed);

        jLabel3.setText("Producto");

        productoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productoBox.addActionListener(this::productoBoxActionPerformed);

        jLabel4.setText("Cantidad");

        cantidadText.setColumns(20);
        cantidadText.setRows(5);
        jScrollPane1.setViewportView(cantidadText);

        añadirBtn.setText("Añadir");
        añadirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirBtnMouseClicked(evt);
            }
        });
        añadirBtn.addActionListener(this::añadirBtnActionPerformed);

        Atras.setText("Atras");
        Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UsuarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(productoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Atras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(añadirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añadirBtn)
                .addGap(18, 18, 18)
                .addComponent(Atras)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioBoxActionPerformed

    private void añadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirBtnActionPerformed

    private void AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseClicked
        frame.mostrar("menu");
    }//GEN-LAST:event_AtrasMouseClicked

    private void productoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoBoxActionPerformed

    private void añadirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirBtnMouseClicked
        String usuarioSeleccionado = (String) UsuarioBox.getSelectedItem();
        String productoSeleccionado = (String) productoBox.getSelectedItem();
        String cantidadStr = cantidadText.getText().trim();

        if(usuarioSeleccionado == null || productoSeleccionado == null || cantidadStr.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione usuario, producto y cantidad");
            return;
        }

        try {
            int cantidad = Integer.parseInt(cantidadStr);
            int idUsuario = obtenerIdUsuario(usuarioSeleccionado);
            int idProducto = obtenerIdProducto(productoSeleccionado);

            if(idUsuario == -1 || idProducto == -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario o producto no encontrado");
                return;
            }

            String URL_CONEXION = "jdbc:h2:mem:testdb";
            try(Connection conn = DriverManager.getConnection(URL_CONEXION, "sa", "password")){
                String sql = "INSERT INTO pedidos (id_usuario, id_producto, cantidad) VALUES (?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, idUsuario);
                pstmt.setInt(2, idProducto);
                pstmt.setInt(3, cantidad);
                int filas = pstmt.executeUpdate();
                if(filas > 0){
                    javax.swing.JOptionPane.showMessageDialog(this, "Pedido agregado correctamente");
                    cantidadText.setText("");
                }
            }

        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Cantidad debe ser un número entero");
        } catch(SQLException e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al insertar el pedido: " + e.getMessage());
        }
    }//GEN-LAST:event_añadirBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JComboBox<String> UsuarioBox;
    private javax.swing.JButton añadirBtn;
    private javax.swing.JTextArea cantidadText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> productoBox;
    // End of variables declaration//GEN-END:variables
}
