package com.adrian.practica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author adria
 */
public class AddProducto extends javax.swing.JPanel {
    
    private MenuFrame frame;
    /**
     * Creates new form AddProducto
     */
    public AddProducto(MenuFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombreText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        precioText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        AñadirProducto = new javax.swing.JButton();
        atras = new javax.swing.JButton();

        jLabel1.setText("Nombre del prodcuto");

        nombreText.setColumns(20);
        nombreText.setRows(5);
        jScrollPane1.setViewportView(nombreText);

        precioText.setColumns(20);
        precioText.setRows(5);
        jScrollPane2.setViewportView(precioText);

        jLabel2.setText("Precio del producto");

        AñadirProducto.setText("Añadir producto");
        AñadirProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirProductoMouseClicked(evt);
            }
        });
        AñadirProducto.addActionListener(this::AñadirProductoActionPerformed);

        atras.setText("Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        atras.addActionListener(this::atrasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AñadirProducto)
                .addGap(18, 18, 18)
                .addComponent(atras)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirProductoActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add yo
    }//GEN-LAST:event_atrasActionPerformed

    private void AñadirProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirProductoMouseClicked
        String nombreProducto = nombreText.getText();
        String precioProducto = precioText.getText();
        if(!nombreProducto.isEmpty() && !precioProducto.isEmpty()){
            String URL_CONEXION = "jdbc:h2:mem:testdb";
            String usuario = "sa";
            String password = "password";
            try{
                Connection conn = DriverManager.getConnection(URL_CONEXION, usuario, password);
                Statement statementAgregar = conn.createStatement();
                String sentenciaSQLAgregar = "INSERT INTO productos (nombre, precio) VALUES (?,?)";
                PreparedStatement pstmtAgregar = conn.prepareStatement(sentenciaSQLAgregar);
                pstmtAgregar.setString(1, nombreProducto);
                pstmtAgregar.setString(2, precioProducto);
                int filasAfectadas = pstmtAgregar.executeUpdate();
                if(filasAfectadas > 0){
                    System.out.println("Se inserto correctamente");
                }else{
                    System.out.println("No se ha podido insertar");
                }
            }catch(SQLException ex){
                Logger.getLogger(AddUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AñadirProductoMouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        frame.mostrar("menu");
    }//GEN-LAST:event_atrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirProducto;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea nombreText;
    private javax.swing.JTextArea precioText;
    // End of variables declaration//GEN-END:variables
}
