/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.adrian.practica;

/**
 *
 * @author adria
 */
public class MenuPrincipal extends javax.swing.JPanel {
    
    private MenuFrame frame;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(MenuFrame frame) {
        this.frame = frame;
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addProducto = new javax.swing.JButton();
        addPedido = new javax.swing.JButton();

        addUsuario.setText("Añadir usuario");
        addUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUsuarioMouseClicked(evt);
            }
        });
        addUsuario.addActionListener(this::addUsuarioActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de Usuarios");

        addProducto.setText("Añadir producto");
        addProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductoMouseClicked(evt);
            }
        });
        addProducto.addActionListener(this::addProductoActionPerformed);

        addPedido.setText("Añadir pedido");
        addPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPedidoMouseClicked(evt);
            }
        });
        addPedido.addActionListener(this::addPedidoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(addUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(addProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(addPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsuarioActionPerformed

    private void addUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsuarioMouseClicked
        frame.mostrar("usuario");
    }//GEN-LAST:event_addUsuarioMouseClicked

    private void addProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductoMouseClicked
        frame.mostrar("producto");
    }//GEN-LAST:event_addProductoMouseClicked

    private void addProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductoActionPerformed

    private void addPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPedidoMouseClicked
        frame.mostrar("pedido");
    }//GEN-LAST:event_addPedidoMouseClicked

    private void addPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPedido;
    private javax.swing.JButton addProducto;
    private javax.swing.JButton addUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
